version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - cargo build

  run:
    desc: Run the project with arguments
    cmds:
      - cargo run -- {{.CLI_ARGS}}

  analyse:
    desc: Analyse the project
    cmds:
      - cargo clippy

  gateway:
    desc: Run the project as a server
    cmds:
      - docker run --rm -it -p 8080:8080 --env-file .env ghcr.io/inference-gateway/inference-gateway:v0.1.15

  test:
    desc: Run the tests
    cmds:
      - cargo test

  install:
    desc: Install the project
    cmds:
      - cargo install --path .

  release:
    desc: Run the release container command locally
    cmds:
      - |
        docker run --rm \
          --cpu-shares=4096 \
          --memory=6g \
          --cpus=4 \
          -v $(pwd):/workspace \
          -v $(pwd)/cache:/kaniko/cache \
          -w /workspace \
          gcr.io/kaniko-project/executor:v1.23.2-debug \
          --dockerfile=./Dockerfile \
          --target=minimal \
          --build-arg=TARGET_ARCH=aarch64-unknown-linux-musl \
          --no-push \
          --no-push-cache \
          --tar-path=/app
